### ISSUE TITLE
Simplify commands

### ISSUE THREAD

**Issue by unional** [typings/generator-typings#32]
```js
{
  "scripts": {
    "build": "typings bundle -o out",
    "lint": "tslint \"**/*.ts\" -e \"source/**\" -e \"out/**\"",
    // `cd` to get around --project limitation running ts-node in NPM script
    "test": "cd test && ts-node test.ts && echo run source tests", 
    "watch": "onchange \"**/*.ts\" -i -e \"out/**\" -- npm -s run lint+build+test",
    "publish": "npm -s run lint+build+test && echo publish to typings/registry",
    "lint+build+test": "npm run lint && npm run build && npm run test",
    "prepublish": "typings install"
  }
}
```
User will typically just:
```sh
npm run watch
# make changes to typings and tests (including source-tests)
# [ctrl+c] to kill `watch`
npm run publish
```
`npm run publish` will not invoke `npm publish` so it will work.

@blakeembrey what do you think?

**Comment by unional** [comment]
Maybe also combine `test` and `source-test` to:
`"test": "echo run source tests && ts-node -n test/test.ts"`

**Comment by blakeembrey** [comment]
Make sure `private: true` is always set, with a name like publish I know I'd mistype it eventually. Aside from that, maybe? What's `source/`?

**Comment by unional** [comment]
Yes. Private: true is always set.

`source` is the source package submodule in. So we can access the source code and tests directly.

Currently we can copy `source/test/*.js` to `source-test/*.ts` manually and run them.
In the future when we can tap into salsa to process `source/test/*.js` automatically.

**Comment by blakeembrey** [comment]
Ah, yes. Forgot about that, cheers! Have you considered not using Git Submodules, but instead using `package.json` with the GitHub reference? I just know Git Submodules have caused issues personally in the past and that might be a reasonable work around having to rely on them. Up to what you're comfortable with, of course.

**Comment by unional** [comment]
> but instead using package.json with the GitHub reference

How does this work?

Either way is fine for me, as long as it is easy for the typings author. :smirk:

I was thinking submodule so that each typings release can correspond to the source submodule commit.

The linked source should be completely read only to the typings author. Is submodule appropriate in this case?

**Comment by blakeembrey** [comment]
Submodule is appropriate, it's just meh. I think the test mode should re-using the source is kind of advanced and probably not needed for most typings projects anyway.

Ref: https://docs.npmjs.com/files/package.json#github-urls

**Comment by unional** [comment]
> Submodule is appropriate, it's just meh. I think the test mode should re-using the source is kind of advanced and probably not needed for most typings projects anyway.

If and when we can tap into salsa, I imagine writing typings would be much simpler with this.
You have all the test cases defined for you and you just need to make them pass. :smirk:

**Comment by unional** [comment]
> Ref: https://docs.npmjs.com/files/package.json#github-urls

So you mean `npm install <source>` using `github-urls`.
One caveat is that the distributed files might not contain test files. 

I already install the source using `npm install <source>`, so using `github-urls` can be a more generalized case for that if it is not delivered through `npm`.

**Comment by blakeembrey** [comment]
> One caveat is that the distributed files might not contain test files.

That's pretty common, but I thought this would fix that by installing directly from the source. I didn't check if it applies NPM ignore things, but I suspected it wouldn't.

**Comment by unional** [comment]
> That's pretty common, but I thought this would fix that by installing directly from the source.

Nope. Basically NPM treat it as a package source. It still reads the `package.json` and install only what's specified. Tested with `npm install chaijs/chai`. Only lib and misc-files are installed.

**Comment by unional** [comment]
NICE! Just start doing `source` and `source-test` for `npm-chai` and already caught some errors. :grin:
