### ISSUE TITLE
Generator kills Cmder due to missing name and version in package.json

### ISSUE THREAD

**Issue by OlsonDev** [typings/generator-typings#55]
I just ran into https://github.com/cmderdev/cmder/issues/700 from running this generator. The root of the issue is package.json is missing a `"name"` and `"version"`. After I manually added those, new Cmder instances could be `cd`'d into my directory.

Obviously this isn't your issue, but I am curious if `"name"` and `"version"` could be defaulted?

![image](https://cloud.githubusercontent.com/assets/308072/14300776/5ad445d2-fb58-11e5-9c11-70babf19c2c6.png)

**Comment by OlsonDev** [comment]
I'm also guessing `"description"` could be defaulted -- I believe `npm` will complain about it.

**Comment by unional** [comment]
Yeah, originally I do have `name`, `version` and `description`, but then took it out as @blakeembrey suggest to keep it minimal.

If it is an issue on certain environment, probably would consider adding those back it.

**Comment by blakeembrey** [comment]
@OlsonDev No need for `name`, `version` or `description` in `package.json`. They are just more stuff you need to keep up to date.

**Comment by blakeembrey** [comment]
@unional I see a typo in the screenshot - should be `DefinitelyTyped` (with a trailing "d").

**Comment by OlsonDev** [comment]
@blakeembrey I already addressed that typo. See https://github.com/typings/generator-typings/pull/54 :rose:

**Comment by OlsonDev** [comment]
> No need for name, version or description in package.json. They are just more stuff you'd need to keep up to date.

@blakeembrey Fair enough; I'll just use `cmd.exe` till there's a release of Cmder with that Lua script fixed. :cry:
