### ISSUE TITLE
Generate a .gitignore file

### ISSUE THREAD

**Issue by OlsonDev** [typings/generator-typings#56]
Having run the generator and then `npm install`, I see a lot of files in `node_modules` & `typings` that should probably be ignored. I'm guessing you (@unional) added the `.gitignore` manually for the `env-electron` [initial commit](https://github.com/typed-typings/env-electron/commit/f8717300b786b2ceb5d79b73e39656490fcfdcda)?

**Comment by unional** [comment]
`.gitignore` should be added by the generator.

**Comment by unional** [comment]
https://github.com/typings/generator-typings/blob/master/generators/current/templates/.gitignore

**Comment by OlsonDev** [comment]
Just test-generated another project. Not seeing a `.gitignore`:

![image](https://cloud.githubusercontent.com/assets/308072/14301528/37ae8850-fb5e-11e5-89fc-0e97139a7804.png)

**Comment by OlsonDev** [comment]
`npm i -g generator-typings` isn't copying your `.gitignore`:

![image](https://cloud.githubusercontent.com/assets/308072/14301729/cb3699a4-fb5f-11e5-80ab-3cc081bf8c24.png)

**Comment by unional** [comment]
Strange, I don't have `.npmignore` You created it?

**Comment by OlsonDev** [comment]
Nope!

**Comment by unional** [comment]
![image](https://cloud.githubusercontent.com/assets/3254987/14301754/3310e20c-fb4f-11e5-8c5e-d1ac2631fd9e.png)

**Comment by unional** [comment]
I do have it created...

**Comment by OlsonDev** [comment]
https://github.com/npm/npm/issues/1862

**Comment by unional** [comment]
What............

**Comment by unional** [comment]
Particular version of npm? or only in Windows?

**Comment by OlsonDev** [comment]
I'm not sure I understand your question. I think if you ran `npm i -g generator-typings` on anything, you'd get a `.npmignore` instead of a `.gitignore` ... I'm still reading the linked issue and its linked issues.

**Comment by OlsonDev** [comment]
For the record, I am on the latest version of npm.

**Comment by unional** [comment]
Ok. Will make a copy of .npmignore === .gitignore

**Comment by OlsonDev** [comment]
When you publish to NPM, lemme know and I'll make sure I get a `.gitignore` in my `templates` directory.

**Comment by unional** [comment]
Pushed

**Comment by OlsonDev** [comment]
Updated to `generator-typings@0.14.8` and still only seeing `.npmignore`.

**Comment by unional** [comment]
I see. Know why

**Comment by unional** [comment]
I think the issue you have only exists on Windows.

because the test was passing on travis. I did have test to check `.gitignore` exists.

**Comment by OlsonDev** [comment]
Looking at others' solution to this issue, they just go with `gitignore` (no dot) or `_gitignore` and then rename it in the generator process.

**Comment by unional** [comment]
Yup

**Comment by unional** [comment]
`0.14.9` should work. Published. Trying it myself.

**Comment by unional** [comment]
Confirmed.

**Comment by unional** [comment]
but.... damn it...

**Comment by unional** [comment]
Now I can close.

`0.14.10`.

**Comment by unional** [comment]
> but.... damn it...

The `_.gitignore` file get copied also. :stuck_out_tongue_winking_eye:

**Comment by unional** [comment]
With `beta` and then `1.0`, the generator is getting quite big.... :worried:

**Comment by OlsonDev** [comment]
I just tested `0.14.10` and it generated a `.npmignore` file AND `.gitignore` file. Was that your intention?

**Comment by unional** [comment]
Yes. What do you think? Don't need the `.npmignore`?

**Comment by unional** [comment]
I'm good either way. As long as the `.gitignore` is in place.

**Comment by OlsonDev** [comment]
No clue, honestly. Just curious if intentional.

**Comment by unional** [comment]
Actually, as an afterthought, yeah, it is not needed. It's private to npm anyway.

**Comment by unional** [comment]
Will remove it on the next relase
