### ISSUE TITLE
Mention tap-spec requirement

### ISSUE THREAD

**Issue by Demurgos** [typings/generator-typings#65]
Hi,
Could-it be possible to mention somewhere (in the `README.md` or the message displayed after the generation) that `npm install -g tap-spec` is required to test the definitions ?

I got an error message and fixed-it immediately so it's not a big deal, but it could improve the user-experience.

(Maybe also add a note for `ts-node` ?)

**Comment by blakeembrey** [comment]
Neither should be installed globally, they should be dev dependencies and the last I saw they were: https://github.com/typings/generator-typings/blob/master/generators/current/templates/template/package.json. Make sure you run `npm install` locally in the generated folder.

**Comment by Demurgos** [comment]
Ok, sorry for my mistake.
I'm not sure how it happened but I effectively forgot to `npm install` in this directory.

**Comment by Demurgos** [comment]
Ok, I understood what happened.
The generator only installs the module being typed but I assumed that it does a full `npm install` when I saw the installation and the `node_modules` directory already there.

**Comment by unional** [comment]
I see. It used to do `npm install` but I removed it because it takes quite a while. I want to give the control back to use asap so they are not blocked by it.
