### ISSUE TITLE
Use npm instead of git submodule to fetch source

### ISSUE THREAD

**Issue by louy** [typings/generator-typings#66]
I really don't see the point of fetching the source as a git submodule instead of just using npm. Git submodule as hard to work with and confusing as hell. Seeing that most of the typings we write are for npm modules I'd rather have the original module be listed as a dependency for my module. E.g. [this one](https://github.com/louy/typed-node-uuid/blob/4d8fa4ae995755f478bc0a1b02cfce4f7d0401c5/package.json#L22).

Any reason for using git submodules then?

**Comment by unional** [comment]
Npm does not fetch source

**Comment by louy** [comment]
I didn't get it. It's only about functionally testing the package isn't it?

**Comment by Demurgos** [comment]
I think it's also for convenience. (Link to source appearing on the Github repo and direct access to the files from your project directory).

**Comment by louy** [comment]
Ah ok. So it's to allow you to copy test files from source [as mentioned here](https://github.com/louy/typed-request/blob/0121620d0c034377fa45ea0b3d018bae008dd8b7/source-test/README.md) and paste them in source-test.
I think you'll have to install the module as an npm dependency anyway so it makes sense this way.

**Comment by unional** [comment]
Yes the package is npm installed to run test already.
