### ISSUE TITLE
Add noImplicitAny in tsconfig.json

### ISSUE THREAD

**Issue by demurgos** [typings/generator-typings#68]
Hi,
Would it be possible to add the `noImplicitAny` compiler options to `tsconfig.json` ?

It would help to ensure that no type is forgotten when we write the typings.

Otherwise, the typings' implicit `any` cause warnings for users choosing to use this option in their main project - and its quite frustrating when warnings are triggered by dependencies.

**Comment by blakeembrey** [comment]
👍 This is absolutely a must. Defaults should be `target: es5`, `declaration: true` and `noImplicitAny: true` to make sure things are written well.

**Comment by unional** [comment]
PR please. :)

**Comment by cyounkins** [comment]
Looks fixed in 4e86528, can close.

**Comment by blakeembrey** [comment]
Correct, thanks. I did do the PR.
